#
#  Scandium - by SolexGames (GrowlyX)
#
communism: true
server-name: "eu-practice"
server:
  settings:
    server-id: "POTCLUBVIP"
redis:
  host: "na1.solexgames.com"
  port: 1234
  password: "testlolhors"
  authentication: true
mongodb:
  url: "mongodb+srv://solexgames:password@na1.solexgames.com/SolexGames?retryWrites=true&w=majority"
whitelisted:
  - GrowlyX
whitelist: true
whitelisted-msg: "&cThis server is currently whitelisted.%NL%&cPlease check our discord for more information."
tips:
  prefix: "&d[TIP] &e"
  messages:
    - ""
