#
#  pCore - by GrowlyX
#
server-name: eu-practice
redis:
  host: "redis-17008.c8.us-east-1-2.ec2.cloud.redislabs.com"
  port: 17008
  password: "WAFEkJpejtb96EtBWmahGWC1ElIRpjv7"
  authentication: true
mongodb:
  url: "mongodb+srv://uhczone:xWjwLmPvCg2wjcAY@cluster0.0fdtt.mongodb.net/potprac?retryWrites=true&w=majority"
