#
#  Scandium - by SolexGames (GrowlyX)
#
motd:
  l1: "&d&lPotClub"
  l2: "&7Practice"
  center: false
server-name: eu-practice
server:
  settings:
    server-id: "POTCLUBVIP"
redis:
  host: "redis-17008.c8.us-east-1-2.ec2.cloud.redislabs.com"
  port: 17008
  password: "WAFEkJpejtb96EtBWmahGWC1ElIRpjv7"
  authentication: true
mongodb:
  url: "mongodb+srv://uhczone:xWjwLmPvCg2wjcAY@cluster0.0fdtt.mongodb.net/potprac?retryWrites=true&w=majority"
