#                     #
#   Core - Database   #
#                     #

MONGODB:
  CONNECTION:
    HOST: ''
    PORT: 27017
    USER: ''
    PASS: ''
REDIS:
  CONNECTION:
    HOST: ''
    PORT: ''
    PASS: 'false'