
name: Scandium
version: SD-1.3.3.7
main: vip.potclub.core.CorePlugin

commands:
  staffchat:
    aliases: [sc]
  options:
    aliases: [globalsettings, gsettings, goptions, coreoptions]
  adminchat:
    aliases: [ac]
  hostchat:
    aliases: [hc]
  devchat:
    aliases: [dc]
  helpop:
    aliases: [request]
  report:
  broadcast:
    aliases: [alert, bc]
  unban:
    aliases: [pardon]
  unmute:
  toggletips:
    aliases: [ttps]
  togglestaffmessages:
    aliases: [tsm]
  punish:
    aliases: [punishment, ban, kick, mute, warn, ipban, blacklist]
  tphere:
    aliases: [s]
  message:
    aliases: [msg, m]
  reply:
    aliases: [r]
  clearchat:
    aliases: [cc]
  mutechat:
    aliases: [mc]
  tppos:
    aliases: [tpposition]
  tp:
    aliases: [teleport, moveto]
  heal:
  kill:
  feed:
  twitter:
  website:
  store:
  discord:
  history:
    aliases: [punishhistory, c]
  ping:
  gmc:
  gms:
  sudo:
  sudoall:
  scandium:
