
name: pCore
main: vip.potclub.core.CorePlugin
version: 1.1
commands:
  staffchat:
    aliases: [sc]
  adminchat:
    aliases: [ac]
  rank:
  hostchat:
    aliases: [hc]
  devchat:
    aliases: [dc]
  helpop:
    aliases: [request]
  broadcast:
    aliases: [alert, bc]
  heal:
  kill:
  feed:
