
name: Scandium
version: SD-1.3.3.7
main: vip.potclub.core.CorePlugin

commands:
  staffchat:
    aliases: [sc]
  adminchat:
    aliases: [ac]
  hostchat:
    aliases: [hc]
  devchat:
    aliases: [dc]
  helpop:
    aliases: [request]
  report:
  broadcast:
    aliases: [alert, bc]
  toggletips:
    aliases: [ttps]
  togglestaffmessages:
    aliases: [tsm]
  punish:
    aliases: [punishment, ban, kick, mute, warn, ipban, blacklist]
  tphere:
    aliases: [s]
  tppos:
    aliases: [tpposition]
  tp:
    aliases: [teleport, moveto]
  heal:
  kill:
  feed:
  ping:
  gmc:
  gms:
  sudo:
  sudoall:
  scandium:
