
name: uSuite
main: vip.potclub.core.CorePlugin
version: 1.3.3.7

commands:
  staffchat:
    aliases: [sc]
  adminchat:
    aliases: [ac]
  hostchat:
    aliases: [hc]
  devchat:
    aliases: [dc]
  helpop:
    aliases: [request]
  broadcast:
    aliases: [alert, bc]
  toggletips:
    aliases: [ttips]
  togglestaffmessages:
    aliases: [tsm]
  heal:
  kill:
  feed:
