
name: uSuite
main: vip.potclub.core.CorePlugin
version: 1.3.3.7
load: STARTUP

commands:
  staffchat:
    aliases: [sc]
  adminchat:
    aliases: [ac]
  hostchat:
    aliases: [hc]
  devchat:
    aliases: [dc]
  helpop:
    aliases: [request]
  report:
  broadcast:
    aliases: [alert, bc]
  toggletips:
    aliases: [ttips]
  togglestaffmessages:
    aliases: [tsm]
  heal:
  kill:
  feed:
  ping:
  gmc:
  gms:
  sudo:
  sudoall:
  tphere:
    aliases: [s]
  tppos:
    aliases: [tpposition]
  tp:
    aliases: [teleport, moveto]

