#
#  Scandium - by SolexGames (GrowlyX)
#
region: "EU"
server-type: "PRACTICE"
server-id: "eu-practice"
refresh-time: 5

settings:
  color-gui: true
  namemc-rewards: true
  namemc-ip: "demo.solexgames.com"
  time-zone: "EST"
  anti-chat-spam: true
  anti-command-spam: true
  automatic-string: "&e&lYou've been automatically put into <value>."
  staff-command-alerts: true
  staff-command-alerts-format: "&7&o[<playername>: &e<message>&7&o]"
  staff-command-alerts-permission: "scandium.staff"
  mod-mode-tag: "&7[S] "
  vanish-tag: "&7[V] "
  punish-gui-enabled: false
  chat-format-enabled: true
  chat-format-type: "NORMAL" # PAPI, NORMAL (The placeholders available in NORMAL won't be available in papi)
  chat-format: "<prefix><rank_prefix><rank_color><custom_color><player_name>&f: &f<message>"

server:
  settings:
    server-id: "SCANDIUM"

messages:
  load-error: "&cAn error occurred while trying to load your data.<nl>&cPlease try again later or contact a staff member."
  server-not-loaded: "&cThe server you've tried to connect to has not loaded.<nl>&cPlease try again in a few seconds or contact staff."
  chat-cooldown: "&cPlease wait another <amount> before chatting again."
  command-cooldown: "&cYou're on command cooldown, please wait <amount>."
  chat-delay-cooldown: "&cPlease wait before chatting again."
  kick-message: "&cYou were kicked for: &7<reason>"
  mute-restricted: "&cYou cannot speak as you are currently muted."

tablist:
  enabled: true
  header: "&7<nl>&e&lMine&3&lArcade<nl>&7www.minearcade.org<nl>&7"
  footer: "&7<nl>&7store.minearcade.org<nl>&7 &7You're currently on &3<server-name>&7! &7<nl>&7"

discord:
  enabled: false
  webhook: ""

core-settings:
  name: "Scandium"
  command-name: "scandium"

# The crypto key should be a randomly generated string.
crypto:
  key: "JRzRsNGvutZbcrrTklcSJsWSQNImMJSqxLZZ"

# Sends to players with the permission "scandium.staff" on join
staff-information:
  - "&b&lStaff &7<nice_char> &3Channel: <channel>"
  - "&b&lStaff &7<nice_char> &3Messages: <messages> &7(/tsm)"
  - "&b&lStaff &7<nice_char> &3Filter: <filter> &7(/tfm)"
  - "&b&lStaff &7<nice_char> &3Mod Mode: <modmode> &7(/mod)"
  - "&b&lStaff &7<nice_char> &3Vanish: <vanish> &7(/vanish)"

tab-block:
  return-enabled: true
  enabled: true
  return:
    - "/scandium:who"
    - "/scandium:list"
  message:
    enabled: false
    string: "&f/scandium:settings, &f/scandium:media"

block-commands:
  enabled: true
  message: 'Unknown command. Type \"/help\" for help.'
  list:
    - "bukkit:plugins"
    - "bukkit:?"
    - "bukkit:help"
    - "bukkit:ver"
    - "bukkit:version"
    - "bukkit:about"
    - "bukkit:pl"
    - "bukkit:msg"
    - "bukkit:kill"
    - "bukkit:tell"
    - "bukkit:me"
    - "minecraft:me"
    - "pl"
    - "plugins"
    - "me"
    - "about"
    - "version"
    - "ver"
    - "icanhasbukkit"

player-join:
  clear-chat: false
  join-message:
    enabled: false
    centered: false
    message:
      - '&6&lWelcome to the Scandium Network!'

freeze-message:
  - " "
  - "&4&lDo not disconnect!"
  - "&cIf you disconnect, you will be punished!"
  - ""
  - "&7You've been frozen by a staff member!"
  - "&7Please connect to &fTeamSpeak &7within &f3 minutes &7or you will"
  - "&7be banned for &cRefusing to Screenshare&7!"
  - " "
tips:
  enabled: true
  padding: true
  interval: 120
  use-prefix: true
  prefix: "&6[TIP] &e"
  messages:
    - "Don't like the pre-made tip broadcasts? &6Check the config!"
    - "Purchase Scandium by contacting one of SolexGame staff! &6GrowlyX#4953"
    - "Want to seek support regarding Scandium? &6Contact GrowlyX#4953"
