name: Scandium
version: ${git.commit.id.abbrev}
main: com.solexgames.core.CorePlugin

api-version: "1.13"
description: ${git.commit.message.full}

load: STARTUP
loadbefore: [
    practice,
]

softdepend: [
    commonlibs-bukkit,
    datacollector-bukkit
]

author: SolexGames
website: https://www.solexgames.com
