name: Scandium
version: ${git.commit.id.abbrev}
main: com.solexgames.core.CorePlugin

api-version: "1.13"
load: STARTUP

loadbefore: [practice]
depend: [commonlibs-bukkit]

author: SolexGames
website: https://www.solexgames.com
