#
#  CoreDatabase Configuration
#
redis:
  host: "127.0.0.1"
  port: 6379
  authentication:
    enabled: false
    password: ""
mongodb:
  url: "mongodb://localhost:27017/SGSoftware?retryWrites=true&w=majority"
