region: "EU"
maintenance: true
whitelistedPlayers:
  - "GrowlyX"
hardMaintenance: false
hardWhitelistedPlayers:
  - "GrowlyX"
  - "threazy"
  - "Beverage"
motd:
  center-automatic: true
  maintenance:
    line-1: "&e&lMine&3&lArcade &7[1.8-1.16]"
    line-2: "&cWe're currently in maintenance mode!"
  normal:
    line-1: "&e&lMine&3&lArcade &7[1.8-1.16]"
    line-2: "&fEvent &7will be starting in &f???&7!"
maintenance-string: "&cSorry, but the server's in maintenance.<nl>&cPlease try logging back in later!"

# https://wiki.vg/Protocol_version_numbers
minimum-protocol: 5
minimum-version: "1.7.x"

# https://wiki.vg/Protocol_version_numbers
maximum-protocol: 47
maximum-version: "1.8.x"

timer-format:
  ended: "&e➥ &6%s &7has commenced, have fun!"
  countdown: "&e%s &7starts in &6%s"

vpn-detector:
  # https://vpnblocker.net/
  api-key: ""
  kick-message: "&cYou cannot use a vpn on our network."
  alerts:
    permission: "xenon.vpn.alerts"
    format: "&b[S] &3[na-proxy] &4%s &ctried to connect with a vpn."
