#
#  Xenon - Created by SolexGames
#
region: "EU"
maintenance: true
whitelistedPlayers:
  - "GrowlyX"
motd:
  maintenance:
    line-1: "&e&lMine&3&lArcade &7[1.8-1.16]"
    line-2: "&cWe're currently in maintenance mode!"
  normal:
    line-1: "&e&lMine&3&lArcade &7[1.8-1.16]"
    line-2: "&fEvent &7will be starting in &f???&7!"
maintenance-string: "&cSorry, but the server's in maintenance.<nl>&cPlease try logging back in later!"
